listener 1883
protocol mqtt

listener 9001
protocol websockets

allow_anonymous false
password_file /mosquitto/config/passwd

persistence true
persistence_location /mosquitto/data/
persistence_file mosquitto.db
persistent_client_expiration 30d
autosave_interval 300

max_inflight_bytes 0
max_inflight_messages 1000
max_queued_bytes 0
max_queued_messages 1000

queue_qos0_messages true

retain_available true

log_dest file /mosquitto/log/mosquitto.log
log_dest stdout
log_type all
log_timestamp true
log_timestamp_format %Y-%m-%dT%H:%M:%S

connection_messages true

keepalive_interval 60

max_packet_size 268435456

set_tcp_nodelay true

per_listener_settings false

capath /etc/ssl/certs
